spec:
  inputs:
    environment:

---
image: mcr.microsoft.com/azure-cli:latest

stages:
  - plan
  - deployPolicy
  - deployRoles

plan:
  stage: plan
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: api://AzureADTokenExchange
  script:
    - az login --service-principal -u "$EPAC_PLAN" --tenant "$AZURE_TENANT_ID" --federated-token "$GITLAB_OIDC_TOKEN" --allow-no-subscriptions > /dev/null 2>&1
    - scripts/deploy/build-deployment-plans.sh --pac-selector "$ENVIRONMENT" --definitions-root Definitions --devops-type gitlab --output-folder "$PAC_OUTPUT_FOLDER"
  artifacts:
    paths:
      - $PAC_OUTPUT_FOLDER
