#!/usr/bin/env bash
# tests/test_azure_resources.sh — Tests for WI-05 azure-resources.sh
# Tests helper functions, scope table building, ownership determination,
# exclusion checking, and structural logic. Resource Graph and REST calls
# are either mocked or tested offline.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/epac.sh"
source "${SCRIPT_DIR}/../lib/azure-resources.sh"

PASS=0
FAIL=0

assert_eq() {
    local desc="$1" expected="$2" actual="$3"
    if [[ "$expected" == "$actual" ]]; then
        echo "  PASS: $desc"
        PASS=$((PASS + 1))
    else
        echo "  FAIL: $desc (expected='$expected', got='$actual')"
        FAIL=$((FAIL + 1))
    fi
}

assert_json_eq() {
    local desc="$1" json="$2" path="$3" expected="$4"
    local actual
    actual="$(echo "$json" | jq -r "$path")"
    assert_eq "$desc" "$expected" "$actual"
}

assert_json_count() {
    local desc="$1" json="$2" path="$3" expected="$4"
    local actual
    actual="$(echo "$json" | jq "$path | length")"
    assert_eq "$desc" "$expected" "$actual"
}

assert_true() {
    local desc="$1" actual="$2"
    assert_eq "$desc" "true" "$actual"
}

assert_false() {
    local desc="$1" actual="$2"
    assert_eq "$desc" "false" "$actual"
}

# ═══════════════════════════════════════════════════════════════════════════════
echo "=== Module load check ==="
assert_eq "azure-resources loaded" "1" "${_EPAC_AZ_RESOURCES_LOADED}"

# ═══════════════════════════════════════════════════════════════════════════════
echo "=== Function availability ==="

for fn in epac_search_az_graph epac_get_policy_resource_properties \
          epac_confirm_pac_owner epac_confirm_policy_resource_exclusions \
          epac_build_scope_table epac_get_policy_or_set_definitions \
          epac_get_policy_assignments epac_get_policy_exemptions \
          epac_get_policy_resources epac_find_non_compliant_resources \
          _epac_new_scope_details _epac_scope_matches_list \
          _epac_build_scope_table_subscription _epac_build_scope_table_mg; do
    if type "$fn" &>/dev/null; then
        echo "  PASS: ${fn} available"
        PASS=$((PASS + 1))
    else
        echo "  FAIL: ${fn} not available"
        FAIL=$((FAIL + 1))
    fi
done

# ═══════════════════════════════════════════════════════════════════════════════
echo "=== epac_get_policy_resource_properties ==="

# Resource with .properties wrapper
resource_with_props='{"id":"/providers/123","type":"policy","properties":{"displayName":"Test","description":"desc"}}'
props="$(epac_get_policy_resource_properties "$resource_with_props")"
assert_json_eq "extracts .properties" "$props" '.displayName' "Test"
assert_json_eq "extracts .description" "$props" '.description' "desc"

# Resource without .properties wrapper (already flat)
resource_flat='{"displayName":"Flat","description":"no wrapper"}'
props_flat="$(epac_get_policy_resource_properties "$resource_flat")"
assert_json_eq "returns object when no .properties" "$props_flat" '.displayName' "Flat"

# ═══════════════════════════════════════════════════════════════════════════════
echo "=== epac_confirm_pac_owner ==="

my_pac_id="my-pac-owner-id-001"

# thisPaC — resource has matching pacOwnerId
res_this='{"properties":{"metadata":{"pacOwnerId":"my-pac-owner-id-001"}}}'
owner="$(epac_confirm_pac_owner "$my_pac_id" "$res_this")"
assert_eq "thisPaC when matching ID" "thisPaC" "$owner"

# otherPaC — resource has different pacOwnerId
res_other='{"properties":{"metadata":{"pacOwnerId":"other-pac-id"}}}'
owner="$(epac_confirm_pac_owner "$my_pac_id" "$res_other")"
assert_eq "otherPaC when different ID" "otherPaC" "$owner"

# unknownOwner — no pacOwnerId in metadata
res_unknown='{"properties":{"metadata":{}}}'
owner="$(epac_confirm_pac_owner "$my_pac_id" "$res_unknown")"
assert_eq "unknownOwner when no ID" "unknownOwner" "$owner"

res_no_meta='{"properties":{}}'
owner="$(epac_confirm_pac_owner "$my_pac_id" "$res_no_meta")"
assert_eq "unknownOwner when no metadata" "unknownOwner" "$owner"

# microsoft — SystemHidden assignment type
res_hidden='{"properties":{"assignmentType":"SystemHidden","metadata":{}}}'
owner="$(epac_confirm_pac_owner "$my_pac_id" "$res_hidden")"
assert_eq "microsoft when SystemHidden" "microsoft" "$owner"

# managedByDfcSecurityPolicies — DfC security pattern
res_dfc_sec='{"properties":{"policyDefinitionId":"/providers/Microsoft.Authorization/policyDefinitions/abc","description":"This object has been generated by Microsoft Defender for Cloud"}}'
scope_sub="/subscriptions/sub-001"
owner="$(epac_confirm_pac_owner "$my_pac_id" "$res_dfc_sec" "$scope_sub")"
assert_eq "managedByDfcSecurityPolicies with DfC pattern" "managedByDfcSecurityPolicies" "$owner"

# managedByDfcDefenderPlans — DfC defender plans pattern
res_dfc_plans='{"properties":{"policyDefinitionId":"/providers/Microsoft.Authorization/policyDefinitions/xyz","description":"This policy assignment was automatically created by Microsoft Defender"}}'
owner="$(epac_confirm_pac_owner "$my_pac_id" "$res_dfc_plans" "$scope_sub")"
assert_eq "managedByDfcDefenderPlans with auto-created pattern" "managedByDfcDefenderPlans" "$owner"

# DfC pattern but at RG scope → unknownOwner (must be subscription scope)
scope_rg="/subscriptions/sub-001/resourceGroups/my-rg"
owner="$(epac_confirm_pac_owner "$my_pac_id" "$res_dfc_sec" "$scope_rg")"
assert_eq "unknownOwner for DfC at RG scope" "unknownOwner" "$owner"

# DfC with no policyDefinitionId → unknownOwner
res_dfc_no_def='{"properties":{"description":"This object has been generated by Microsoft Defender for Cloud"}}'
owner="$(epac_confirm_pac_owner "$my_pac_id" "$res_dfc_no_def" "$scope_sub")"
assert_eq "unknownOwner for DfC without policyDefinitionId" "unknownOwner" "$owner"

# ═══════════════════════════════════════════════════════════════════════════════
echo "=== _epac_scope_matches_list ==="

patterns='["/providers/Microsoft.Management/managementGroups/mg1", "/subscriptions/sub-001"]'

result="$(_epac_scope_matches_list "/providers/Microsoft.Management/managementGroups/mg1" "$patterns")"
assert_true "matches exact MG" "$result"

result="$(_epac_scope_matches_list "/PROVIDERS/MICROSOFT.MANAGEMENT/MANAGEMENTGROUPS/MG1" "$patterns")"
assert_true "matches case-insensitive MG" "$result"

result="$(_epac_scope_matches_list "/subscriptions/sub-001" "$patterns")"
assert_true "matches exact subscription" "$result"

result="$(_epac_scope_matches_list "/subscriptions/sub-002" "$patterns")"
assert_false "no match for different sub" "$result"

result="$(_epac_scope_matches_list "/some/other/scope" "[]")"
assert_false "no match with empty list" "$result"

# ═══════════════════════════════════════════════════════════════════════════════
echo "=== epac_confirm_policy_resource_exclusions ==="

# Simple scope table
scope_table='{
    "/subscriptions/sub-001": {"id": "/subscriptions/sub-001"},
    "/subscriptions/sub-002": {"id": "/subscriptions/sub-002"},
    "/subscriptions/sub-001/resourceGroups/rg1": {"id": "/subscriptions/sub-001/resourceGroups/rg1"}
}'
excluded_scopes='["/subscriptions/sub-002"]'
excluded_ids='["/subscriptions/*/resourceGroups/rg-deleted*"]'

# Included — scope in table, not excluded
test_id="/subscriptions/sub-001/providers/Microsoft.Authorization/policyDefinitions/my-def"
result="$(epac_confirm_policy_resource_exclusions "$test_id" "$test_id" "$scope_table" "$excluded_scopes" "$excluded_ids")"
assert_true "included when scope is valid" "$result"

# Built-in resources always included
test_id="/providers/Microsoft.Authorization/policyDefinitions/built-in"
result="$(epac_confirm_policy_resource_exclusions "$test_id" "$test_id" "$scope_table" "$excluded_scopes" "$excluded_ids")"
assert_true "built-in always included" "$result"

# Excluded by scope
test_id="/subscriptions/sub-002/providers/Microsoft.Authorization/policyDefinitions/my-def"
result="$(epac_confirm_policy_resource_exclusions "$test_id" "$test_id" "$scope_table" "$excluded_scopes" "$excluded_ids")"
assert_false "excluded by scope" "$result"

# Excluded by ID pattern (wildcard)
test_id="/subscriptions/sub-001/resourceGroups/rg-deleted-abc/providers/Microsoft.Authorization/policyDefinitions/x"
result="$(epac_confirm_policy_resource_exclusions "$test_id" "$test_id" "$scope_table" "$excluded_scopes" "$excluded_ids")"
assert_false "excluded by wildcard pattern" "$result"

# Not in scope table
test_id="/subscriptions/sub-999/providers/Microsoft.Authorization/policyDefinitions/my-def"
result="$(epac_confirm_policy_resource_exclusions "$test_id" "$test_id" "$scope_table" "$excluded_scopes" "$excluded_ids")"
assert_false "excluded when scope not in table" "$result"

# ═══════════════════════════════════════════════════════════════════════════════
echo "=== _epac_new_scope_details ==="

scope="$(_epac_new_scope_details "/subscriptions/sub1" "Microsoft.Resources/subscriptions" "sub1" "My Subscription" "false" "true" "Enabled" "eastus")"

assert_json_eq "scope id" "$scope" '.id' "/subscriptions/sub1"
assert_json_eq "scope type" "$scope" '.type' "Microsoft.Resources/subscriptions"
assert_json_eq "scope name" "$scope" '.name' "sub1"
assert_json_eq "scope displayName" "$scope" '.displayName' "My Subscription"
assert_json_eq "scope isExcluded" "$scope" '.isExcluded' "false"
assert_json_eq "scope isInGlobalNotScope" "$scope" '.isInGlobalNotScope' "true"
assert_json_eq "scope state" "$scope" '.state' "Enabled"
assert_json_eq "scope location" "$scope" '.location' "eastus"
assert_json_count "parentTable empty" "$scope" '.parentTable' "0"
assert_json_count "childrenTable empty" "$scope" '.childrenTable' "0"
assert_json_count "resourceGroupsTable empty" "$scope" '.resourceGroupsTable' "0"
assert_json_count "notScopesList empty" "$scope" '.notScopesList' "0"

# Defaults
scope_default="$(_epac_new_scope_details "/mgid" "mg" "mgname")"
assert_json_eq "default displayName is name" "$scope_default" '.displayName' "mgname"
assert_json_eq "default isExcluded" "$scope_default" '.isExcluded' "false"
assert_json_eq "default state" "$scope_default" '.state' "Enabled"
assert_json_eq "default location" "$scope_default" '.location' "global"

# ═══════════════════════════════════════════════════════════════════════════════
echo "=== _epac_build_scope_table_subscription ==="

# Mock pac environment
pac_env='{
    "deploymentRootScope": "/providers/Microsoft.Management/managementGroups/root",
    "desiredState": {
        "excludeSubscriptions": false,
        "globalExcludedScopesSubscriptions": [],
        "globalExcludedScopesResourceGroups": ["/subscriptions/sub-001/resourceGroups/rg-excluded"]
    },
    "globalNotScopesSubscriptions": [],
    "globalNotScopesResourceGroups": []
}'

# Mock resource groups by subscription
rg_by_sub='{
    "sub-001": [
        {"id":"/subscriptions/sub-001/resourceGroups/rg1","name":"rg1","location":"eastus"},
        {"id":"/subscriptions/sub-001/resourceGroups/rg-excluded","name":"rg-excluded","location":"westus"}
    ]
}'

st="$(_epac_build_scope_table_subscription "sub-001" "My Sub" "$rg_by_sub" "$pac_env" "{}")"

# Subscription entry
assert_json_eq "sub entry exists" "$st" 'has("/subscriptions/sub-001")' "true"
assert_json_eq "sub type" "$st" '.["/subscriptions/sub-001"].type' "Microsoft.Resources/subscriptions"
assert_json_eq "sub name" "$st" '.["/subscriptions/sub-001"].name' "sub-001"
assert_json_eq "sub displayName" "$st" '.["/subscriptions/sub-001"].displayName' "My Sub"

# Resource group entries
assert_json_eq "rg1 entry exists" "$st" 'has("/subscriptions/sub-001/resourceGroups/rg1")' "true"
assert_json_eq "rg1 location" "$st" '.["/subscriptions/sub-001/resourceGroups/rg1"].location' "eastus"
assert_json_eq "rg1 isExcluded" "$st" '.["/subscriptions/sub-001/resourceGroups/rg1"].isExcluded' "false"

# Excluded resource group
assert_json_eq "rg-excluded entry exists" "$st" 'has("/subscriptions/sub-001/resourceGroups/rg-excluded")' "true"
assert_json_eq "rg-excluded isExcluded" "$st" '.["/subscriptions/sub-001/resourceGroups/rg-excluded"].isExcluded' "true"

# Resource groups table on subscription entry
assert_json_eq "sub has 2 RGs" "$st" '.["/subscriptions/sub-001"].resourceGroupsTable | length' "2"

# ═══════════════════════════════════════════════════════════════════════════════
echo "=== _epac_build_scope_table_subscription (excluded subscription) ==="

pac_env_excl='{
    "deploymentRootScope": "/providers/Microsoft.Management/managementGroups/root",
    "desiredState": {
        "excludeSubscriptions": true,
        "globalExcludedScopesSubscriptions": [],
        "globalExcludedScopesResourceGroups": []
    },
    "globalNotScopesSubscriptions": [],
    "globalNotScopesResourceGroups": []
}'

st_excl="$(_epac_build_scope_table_subscription "sub-002" "Excluded Sub" '{}' "$pac_env_excl" "{}")"
assert_json_eq "excluded sub isExcluded" "$st_excl" '.["/subscriptions/sub-002"].isExcluded' "true"

# ═══════════════════════════════════════════════════════════════════════════════
echo "=== _epac_build_scope_table_subscription (globalNotScopes) ==="

pac_env_gns='{
    "deploymentRootScope": "/providers/Microsoft.Management/managementGroups/root",
    "desiredState": {
        "excludeSubscriptions": false,
        "globalExcludedScopesSubscriptions": [],
        "globalExcludedScopesResourceGroups": []
    },
    "globalNotScopesSubscriptions": ["/subscriptions/sub-003"],
    "globalNotScopesResourceGroups": []
}'

st_gns="$(_epac_build_scope_table_subscription "sub-003" "GNS Sub" '{}' "$pac_env_gns" "{}")"
assert_json_eq "globalNotScope sub isInGlobalNotScope" "$st_gns" '.["/subscriptions/sub-003"].isInGlobalNotScope' "true"

# ═══════════════════════════════════════════════════════════════════════════════
echo "=== _epac_build_scope_table_mg ==="

# Mock management group hierarchy
mg_hierarchy='{
    "id": "/providers/Microsoft.Management/managementGroups/root-mg",
    "name": "root-mg",
    "properties": {
        "displayName": "Root MG",
        "children": [
            {
                "id": "/providers/Microsoft.Management/managementGroups/child-mg",
                "name": "child-mg",
                "type": "Microsoft.Management/managementGroups",
                "displayName": "Child MG",
                "properties": {
                    "displayName": "Child MG",
                    "children": []
                }
            },
            {
                "id": "/subscriptions/sub-100",
                "name": "sub-100",
                "type": "/subscriptions",
                "displayName": "Sub 100"
            }
        ]
    }
}'

pac_env_mg='{
    "deploymentRootScope": "/providers/Microsoft.Management/managementGroups/root-mg",
    "desiredState": {
        "excludeSubscriptions": false,
        "globalExcludedScopesSubscriptions": [],
        "globalExcludedScopesResourceGroups": [],
        "globalExcludedScopesManagementGroups": []
    },
    "globalNotScopesSubscriptions": [],
    "globalNotScopesResourceGroups": [],
    "globalNotScopesManagementGroups": []
}'

rg_by_sub_mg='{"sub-100": [{"id":"/subscriptions/sub-100/resourceGroups/rg-a","name":"rg-a","location":"westus2"}]}'

st_mg="$(_epac_build_scope_table_mg "$mg_hierarchy" "$rg_by_sub_mg" "$pac_env_mg" "{}")"

# Root MG
assert_json_eq "root-mg exists" "$st_mg" 'has("/providers/Microsoft.Management/managementGroups/root-mg")' "true"
assert_json_eq "root-mg displayName" "$st_mg" '.["/providers/Microsoft.Management/managementGroups/root-mg"].displayName' "Root MG"

# Child MG
assert_json_eq "child-mg exists" "$st_mg" 'has("/providers/Microsoft.Management/managementGroups/child-mg")' "true"
assert_json_eq "child-mg displayName" "$st_mg" '.["/providers/Microsoft.Management/managementGroups/child-mg"].displayName' "Child MG"

# Subscription under MG
assert_json_eq "sub-100 exists" "$st_mg" 'has("/subscriptions/sub-100")' "true"
assert_json_eq "sub-100 displayName" "$st_mg" '.["/subscriptions/sub-100"].displayName' "Sub 100"

# Resource group under subscription
assert_json_eq "rg-a exists" "$st_mg" 'has("/subscriptions/sub-100/resourceGroups/rg-a")' "true"

# Children table on root
assert_json_count "root has 2 children" "$st_mg" '.["/providers/Microsoft.Management/managementGroups/root-mg"].childrenTable' "2"

# Parent table on child-mg
assert_json_eq "child-mg parent includes root" "$st_mg" '.["/providers/Microsoft.Management/managementGroups/child-mg"].parentTable | has("/providers/Microsoft.Management/managementGroups/root-mg")' "true"

# Parent table on subscription
assert_json_eq "sub parent includes root" "$st_mg" '.["/subscriptions/sub-100"].parentTable | has("/providers/Microsoft.Management/managementGroups/root-mg")' "true"

# ═══════════════════════════════════════════════════════════════════════════════
echo "=== _epac_build_scope_table_mg (excluded MG) ==="

pac_env_ex_mg='{
    "deploymentRootScope": "/providers/Microsoft.Management/managementGroups/root-mg",
    "desiredState": {
        "excludeSubscriptions": false,
        "globalExcludedScopesSubscriptions": [],
        "globalExcludedScopesResourceGroups": [],
        "globalExcludedScopesManagementGroups": ["/providers/Microsoft.Management/managementGroups/child-mg"]
    },
    "globalNotScopesSubscriptions": [],
    "globalNotScopesResourceGroups": [],
    "globalNotScopesManagementGroups": []
}'

st_ex_mg="$(_epac_build_scope_table_mg "$mg_hierarchy" '{}' "$pac_env_ex_mg" "{}")"
assert_json_eq "excluded child-mg isExcluded" "$st_ex_mg" '.["/providers/Microsoft.Management/managementGroups/child-mg"].isExcluded' "true"
assert_json_eq "root not excluded" "$st_ex_mg" '.["/providers/Microsoft.Management/managementGroups/root-mg"].isExcluded' "false"

# ═══════════════════════════════════════════════════════════════════════════════
echo "=== _epac_build_scope_table_mg (globalNotScopes MG) ==="

pac_env_gns_mg='{
    "deploymentRootScope": "/providers/Microsoft.Management/managementGroups/root-mg",
    "desiredState": {
        "excludeSubscriptions": false,
        "globalExcludedScopesSubscriptions": [],
        "globalExcludedScopesResourceGroups": [],
        "globalExcludedScopesManagementGroups": []
    },
    "globalNotScopesSubscriptions": [],
    "globalNotScopesResourceGroups": [],
    "globalNotScopesManagementGroups": ["/providers/Microsoft.Management/managementGroups/root-mg"]
}'

st_gns_mg="$(_epac_build_scope_table_mg "$mg_hierarchy" '{}' "$pac_env_gns_mg" "{}")"
assert_json_eq "root-mg globalNotScope" "$st_gns_mg" '.["/providers/Microsoft.Management/managementGroups/root-mg"].isInGlobalNotScope' "true"

# ═══════════════════════════════════════════════════════════════════════════════
echo "=== epac_confirm_pac_owner edge cases ==="

# Flat resource (no .properties wrapper) with pacOwnerId
res_flat_with_pac='{"metadata":{"pacOwnerId":"my-pac-owner-id-001"}}'
owner="$(epac_confirm_pac_owner "$my_pac_id" "$res_flat_with_pac")"
assert_eq "thisPaC with flat resource" "thisPaC" "$owner"

# Microsoft hidden takes precedence over pacOwnerId
res_hidden_with_pac='{"properties":{"assignmentType":"SystemHidden","metadata":{"pacOwnerId":"my-pac-owner-id-001"}}}'
owner="$(epac_confirm_pac_owner "$my_pac_id" "$res_hidden_with_pac")"
assert_eq "microsoft takes precedence over pac owner" "microsoft" "$owner"

# ═══════════════════════════════════════════════════════════════════════════════
echo "=== Scope table parent propagation ==="

# Subscription under MG should get parent table that includes MG
mg_simple='{
    "id": "/providers/Microsoft.Management/managementGroups/parent-mg",
    "name": "parent-mg",
    "properties": {
        "displayName": "Parent MG",
        "children": [
            {
                "id": "/subscriptions/sub-200",
                "name": "sub-200",
                "type": "/subscriptions",
                "displayName": "Sub 200"
            }
        ]
    }
}'

pac_env_simple='{
    "deploymentRootScope": "/providers/Microsoft.Management/managementGroups/parent-mg",
    "desiredState": {
        "excludeSubscriptions": false,
        "globalExcludedScopesSubscriptions": [],
        "globalExcludedScopesResourceGroups": [],
        "globalExcludedScopesManagementGroups": []
    },
    "globalNotScopesSubscriptions": [],
    "globalNotScopesResourceGroups": [],
    "globalNotScopesManagementGroups": []
}'

rg_for_simple='{"sub-200":[{"id":"/subscriptions/sub-200/resourceGroups/rg-b","name":"rg-b","location":"northeurope"}]}'
st_parent="$(_epac_build_scope_table_mg "$mg_simple" "$rg_for_simple" "$pac_env_simple" "{}")"

# RG should be a grandchild: parent table should include both sub and MG
assert_json_eq "rg-b parent has sub" "$st_parent" '.["/subscriptions/sub-200/resourceGroups/rg-b"].parentTable | has("/subscriptions/sub-200")' "true"
assert_json_eq "rg-b parent has mg" "$st_parent" '.["/subscriptions/sub-200/resourceGroups/rg-b"].parentTable | has("/providers/Microsoft.Management/managementGroups/parent-mg")' "true"

# ═══════════════════════════════════════════════════════════════════════════════
echo "=== exclusion wildcard patterns ==="

scope_table_ex='{
    "/subscriptions/sub-001": {},
    "/subscriptions/sub-001/resourceGroups/rg1": {}
}'

# Test diverse wildcard patterns
excluded_ids_diverse='["/subscriptions/*/providers/Microsoft.Authorization/policyAssignments/test-*"]'

test_id_match="/subscriptions/sub-001/providers/Microsoft.Authorization/policyAssignments/test-assignment-1"
result="$(epac_confirm_policy_resource_exclusions "$test_id_match" "$test_id_match" "$scope_table_ex" '[]' "$excluded_ids_diverse")"
assert_false "excluded by mid-path wildcard" "$result"

test_id_nomatch="/subscriptions/sub-001/providers/Microsoft.Authorization/policyAssignments/other-assignment"
result="$(epac_confirm_policy_resource_exclusions "$test_id_nomatch" "$test_id_nomatch" "$scope_table_ex" '[]' "$excluded_ids_diverse")"
assert_true "not excluded, no pattern match" "$result"

# Case insensitive wildcard
test_id_upper="/SUBSCRIPTIONS/SUB-001/PROVIDERS/MICROSOFT.AUTHORIZATION/POLICYASSIGNMENTS/TEST-SOMETHING"
result="$(epac_confirm_policy_resource_exclusions "$test_id_upper" "$test_id_upper" "$scope_table_ex" '[]' "$excluded_ids_diverse")"
assert_false "excluded by wildcard case-insensitive" "$result"

# ═══════════════════════════════════════════════════════════════════════════════
echo "=== _epac_new_scope_details helper structure ==="

details="$(_epac_new_scope_details "/test/id" "TestType" "testname" "Test Display" "true" "true" "Disabled" "westus2")"

# Verify all fields
assert_json_eq "details id" "$details" '.id' "/test/id"
assert_json_eq "details type" "$details" '.type' "TestType"
assert_json_eq "details name" "$details" '.name' "testname"
assert_json_eq "details displayName" "$details" '.displayName' "Test Display"
assert_json_eq "details isExcluded true" "$details" '.isExcluded' "true"
assert_json_eq "details isInGlobalNotScope true" "$details" '.isInGlobalNotScope' "true"
assert_json_eq "details state Disabled" "$details" '.state' "Disabled"
assert_json_eq "details location westus2" "$details" '.location' "westus2"
assert_json_eq "details notScopesTable empty obj" "$details" '.notScopesTable | type' "object"
assert_json_eq "details excludedScopesTable empty obj" "$details" '.excludedScopesTable | type' "object"

# ═══════════════════════════════════════════════════════════════════════════════
echo "=== Multiple RGs across subscriptions ==="

pac_env_multi='{
    "deploymentRootScope": "/providers/Microsoft.Management/managementGroups/root",
    "desiredState": {
        "excludeSubscriptions": false,
        "globalExcludedScopesSubscriptions": [],
        "globalExcludedScopesResourceGroups": []
    },
    "globalNotScopesSubscriptions": [],
    "globalNotScopesResourceGroups": []
}'

rg_multi='{
    "sub-a": [
        {"id":"/subscriptions/sub-a/resourceGroups/rg1","name":"rg1","location":"eastus"},
        {"id":"/subscriptions/sub-a/resourceGroups/rg2","name":"rg2","location":"westus"},
        {"id":"/subscriptions/sub-a/resourceGroups/rg3","name":"rg3","location":"westus2"}
    ]
}'

st_multi="$(_epac_build_scope_table_subscription "sub-a" "Sub A" "$rg_multi" "$pac_env_multi" "{}")"
assert_json_count "sub-a has 3 RGs" "$st_multi" '.["/subscriptions/sub-a"].resourceGroupsTable' "3"
assert_eq "total entries = sub + 3 RGs" "4" "$(echo "$st_multi" | jq 'keys | length')"

# ═══════════════════════════════════════════════════════════════════════════════
echo "=== Exclusion propagation to child RGs ==="

pac_env_prop='{
    "deploymentRootScope": "/providers/Microsoft.Management/managementGroups/root",
    "desiredState": {
        "excludeSubscriptions": false,
        "globalExcludedScopesSubscriptions": ["/subscriptions/sub-excl"],
        "globalExcludedScopesResourceGroups": []
    },
    "globalNotScopesSubscriptions": [],
    "globalNotScopesResourceGroups": []
}'

rg_prop='{"sub-excl":[{"id":"/subscriptions/sub-excl/resourceGroups/rg-child","name":"rg-child","location":"uk"}]}'
st_prop="$(_epac_build_scope_table_subscription "sub-excl" "Excluded Sub" "$rg_prop" "$pac_env_prop" "{}")"
assert_json_eq "child RG inherits excluded" "$st_prop" '.["/subscriptions/sub-excl/resourceGroups/rg-child"].isExcluded' "true"

# ═══════════════════════════════════════════════════════════════════════════════
echo "=== epac_set_unique_role_assignment_scopes ==="

role_scopes='{"subscriptions":{},"managementGroups":{},"resourceGroups":{},"resources":{},"unknown":{}}'
role_scopes="$(epac_set_unique_role_assignment_scopes "/subscriptions/sub1" "$role_scopes")"
assert_json_eq "subscription scope classified" "$role_scopes" '.subscriptions["/subscriptions/sub1"]' 'subscriptions'

role_scopes="$(epac_set_unique_role_assignment_scopes "/subscriptions/sub1/resourceGroups/rg1" "$role_scopes")"
assert_json_eq "resourceGroups scope classified" "$role_scopes" '.resourceGroups["/subscriptions/sub1/resourceGroups/rg1"]' 'resourceGroups'

role_scopes="$(epac_set_unique_role_assignment_scopes "/subscriptions/sub1/resourceGroups/rg1/providers/Microsoft.Compute/virtualMachines/vm1" "$role_scopes")"
assert_json_eq "resources scope classified" "$role_scopes" '.resources["/subscriptions/sub1/resourceGroups/rg1/providers/Microsoft.Compute/virtualMachines/vm1"]' 'resources'

# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo "================================================================="
echo "  RESULTS: ${PASS} passed, ${FAIL} failed"
echo "================================================================="

[[ $FAIL -eq 0 ]] && exit 0 || exit 1
